name = "LDrawParser"
uuid = "c9062c12-fdd7-47de-ae43-3b8a76d3a662"
authors = ["kylebrown <kylejbrown17@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
