name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.4'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: webfactory/ssh-agent@v0.4.1 # Use to add private ssh key to match deploy key
        with:
          ssh-private-key: ${{ secrets.JULIA_PACKAGE_REGISTRY_KEY }}
      - run: julia -e 'using Pkg; pkg"registry add git@github.com:kylejbrown17/JuliaPackageRegistry.git"'
      - run: ls ~/.julia/registries
      # - uses: julia-actions/julia-buildpkg@v1
      # - uses: julia-actions/julia-runtest@v1
      - run: | 
          julia -e '
            using Pkg
            pkg"dev https://github.com/kylejbrown17/GraphUtils.jl.git"
            Pkg.activate(".")
            Pkg.build()
            Pkg.test()'
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.activate(pwd())
            pkg"add https://github.com/kylejbrown17/GraphUtils.jl.git"
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
